### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by risaueno** [wesselb/stheno#3]
`import stheno` gives error "ImportError: /data/hpcdata/users/risno/miniconda3/envs/stheno/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so)" 

**Steps taken**

On a fresh conda installation, I did: 
```
conda install -c anaconda gcc
conda install -c anaconda gfortran_linux-64
conda install tensorflow-gpu  # this installs 2.0
pip install stheno
python -c "import stheno"
```

The first 3 lines attempt to follow the installation instructions. Perhaps this is the wrong way to install gcc and gfortran? Installation instructions suggest `conda install gcc` but this gives `PackagesNotFoundError` error.

Full error message: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/stheno/__init__.py", line 11, in <module>
    from .mean import *
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/stheno/mean.py", line 7, in <module>
    import tensorflow as tf
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /data/hpcdata/users/risno/miniconda3/envs/stheno/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/hpcdata/users/risno/miniconda3/envs/stheno/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so)
```

OS version:
Linux bslws05 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core

**Comment by wesselb** [comment]
Great to hear that you managed to figure it out. I'm not entirely sure why conda is behaving in the way that it does. Probably worth looking into.

I indeed removed the explicit dependencies on AutoGrad and TensorFlow, so that users can install only the extensions that they need.

Do let me know if you run into any other issues.
