### ISSUE TITLE
problem installing stheno in windows 10 using anaconda 

### ISSUE THREAD

**Issue by erikcong80** [wesselb/stheno#6]
Hi, 

I have installed gfortran in windows 10 by installing mingw-64. In my anaconda command line, I am able to compile code using gfortran. However, when I tried pip install stheno, following error occurs: 
ERROR: Command errored out with exit status 1:
   command: 'D:\Anaconda\bin\envs\cosimo_pytorch\python.exe' 'D:\Anaconda\bin\envs\cosimo_pytorch\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\XIAN_L~1\AppData\Local\Temp\tmp7uvkgbia'
       cwd: C:\Users\XIAN_L~1\AppData\Local\Temp\pip-install-l5cmtk4q\backends
  Complete output (20 lines):
  Der Befehl "which" ist entweder falsch geschrieben oder
  konnte nicht gefunden werden.
  Traceback (most recent call last):
    File "D:\Anaconda\bin\envs\cosimo_pytorch\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "D:\Anaconda\bin\envs\cosimo_pytorch\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\Anaconda\bin\envs\cosimo_pytorch\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\XIAN_L~1\AppData\Local\Temp\pip-build-env-c_j_teqt\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\XIAN_L~1\AppData\Local\Temp\pip-build-env-c_j_teqt\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\XIAN_L~1\AppData\Local\Temp\pip-build-env-c_j_teqt\overlay\Lib\site-packages\setuptools\build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\XIAN_L~1\AppData\Local\Temp\pip-build-env-c_j_teqt\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 10, in <module>
      raise RuntimeError('gfortran cannot be found. Please install gfortran. '
  RuntimeError: gfortran cannot be found. Please install gfortran. On OS X, this can be done with "brew install gcc". On Linux, "apt-get install gfortran" should suffice.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Anaconda\bin\envs\cosimo_pytorch\python.exe' 'D:\Anaconda\bin\envs\cosimo_pytorch\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\XIAN_L~1\AppData\Local\Temp\tmp7uvkgbia' Check the logs for full command output.

I have already set up my windows path after installing minGW for program to locate gfortran compiler. 

Any help will be grateful.

**Comment by wesselb** [comment]
Hey Erik! Could you check whether the command line tool `which` is available on minGW? The installation script uses `which` to detect the availability commands, but `which` appears to not be available.

**Comment by patel-zeel** [comment]
This issue still persists. I have tried a bunch of tools similar to minGW including it, but installation was never successful. Some of my colleagues are also facing the same issue. I was trying to install stheno on Windows to quickly play around with some advanced IDEs such as PyCharm. A Windows compatible ```pip install stheno``` would be a great addition. As a note, I have also tried to use ```where``` command in Windows 10 by setting its alias as ```which``` but it didn't work.

I would love to hear from @erikcong80 if he has already found a workaround.

**Comment by wesselb** [comment]
If there's a demand for compatibility with Windows, then I can look into that. I imagine that it shouldn't be too hard. I may not get to this on the very short term, but I'll put it on the priority list.
